# Generated by Django 3.2 on 2023-07-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_auto_20230717_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmodel',
            name='readwho',
            field=models.CharField(blank=True, default='a', max_length=200, null=True),
        ),
    ]
